### ISSUE TITLE
avoid link rot / broken links

### ISSUE THREAD

**Issue by lnnrtwttkhn** [lnnrtwttkhn/version-control-book#145]
We should make an effort to avoid [link rot](https://en.wikipedia.org/wiki/Link_rot), or dead / broken links.

To do this, I would like to do the following:

- [ ] Add all external links to a new `_links.yml` file (similar to `_variables.yml`, see [Quarto documentation](https://quarto.org/docs/authoring/variables.html)) and then include the variable in the documents
- [ ] For this, I would also rename the `links` entries in `_variables.yml` to `project`, so that `{{< links.SOMETHING >}}` is reserved for external links
- [ ] Add a small script that checks the availability for all external links in `_links.yml`. Quarto [checks for *internal* links](https://github.com/quarto-dev/quarto-cli/issues/1319) but not external links. I imagine that the script could quickly read all the links from the `_links.yml` and check if they are available of not.

**Comment by aaronpeikert** [comment]
Hey I just stumbled across this and thought I'd mention that I solved it without changing anything in how to use links in quarto but rather used this nice little library that accepts markdown.

```
linkchecker:
  stage: validate
  image:
    name: ghcr.io/tcort/markdown-link-check:3.11.2
    entrypoint: ["/bin/sh", "-c"]
  script:
  - quarto render
    - find . \( -name '*.qmd' -o -name '*.md' \) -print0 | xargs -0 -n1 markdown-link-check
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" || $CI_PIPELINE_SOURCE == "merge_request_event"'
```
