### ISSUE TITLE
branches chapter rendering is odd

### ISSUE THREAD

**Issue by lnnrtwttkhn** [lnnrtwttkhn/version-control-book#71]
github actions [crashes](https://github.com/lnnrtwttkhn/version-control-book/actions/runs/7213820092/job/19654533746)

adding:

```yaml
engine: knitr
execute:
  eval: false
```

to the yaml header, fixes it. but this is not necessary for all other chapters.

weird, but I will apply this as a hotfix
